### ISSUE TITLE
sampleLod function?

### ISSUE THREAD

**Issue by Askhento** [aferriss/sparksl-shader-examples#1]
It does not seem to work, or I have no idea how to use it.

**Comment by aferriss** [comment]
Hi @Askhento, the sample Lod function works like this: `tex.sampleLod(uv, lodLevel)` where lod level is the level of detail that you want (typically an int between 0-8ish).

However, it does appear to be broken at the moment, so hopefully they will fix it in a future release.

**Comment by Askhento** [comment]
@aferriss So that is why you didn't add it. Does it should work the same as size parameter for ShaderRenderPass in PatchEditor?

**Comment by aferriss** [comment]
Hi @Askhento, I'm not sure I understand your question

**Comment by Askhento** [comment]
I mean size here. Does this function works the same?
<img width="220" alt="image" src="https://user-images.githubusercontent.com/34323808/102690528-d5058a80-4227-11eb-871a-d45f32c423ef.png">

**Comment by aferriss** [comment]
@Askhento that size represents the size of the render pass. If you change it to fixed mode the size is measured in pixels. Screen mode is a percentage of the screen size.

Sample lod works differently than just resizing the render target. You can play around with it on shadertoy.com using texture(iChannel0, uv, lod level); for an approximation

**Comment by aferriss** [comment]
Going to close this for now but feel free to reopen if you've got further questions

**Comment by aferriss** [comment]
@Askhento I added an example of using sampleLod here if you're still interested in using it! 

https://github.com/aferriss/sparksl-shader-examples/tree/master/6-builtins/sampleLod

**Comment by Askhento** [comment]
@aferriss 
HI, thanks. I am still confused a lot with the difference between lod and size.
Made a test with both side by side. They seems to do the same stuff except lod is int, but size is float. 
The good thing I see is that now I can use lod as Uniform))) 
<img width="355" alt="image" src="https://user-images.githubusercontent.com/34323808/105613932-84192100-5de7-11eb-92d1-a2e0b92dc225.png">
