### ISSUE TITLE
Sdf example wrong number of arguments in Pro tip

### ISSUE THREAD

**Issue by Askhento** [aferriss/sparksl-shader-examples#3]
```
  // PROTIP!!! You can create the sdf on a single line with an extra set of brackets in your syntax
  // For example, the two lines above could be combined into the line below. Note the (uv) at the end
  // float poly = sdfPolygon(vec2(0.5), texel.x*50.0, 5.0)(uv);

                                                       ^
                                            here function should have only 2 args, but 5.0 found, which give unknown error!

```

**Comment by aferriss** [comment]
Hi @Askhento , 

Are you sure? The docs lists three arguments for sdfPolygon
https://sparkar.facebook.com/ar-studio/learn/sparksl/sparksl-api/sdf#enums
<img width="810" alt="Screen Shot 2021-01-26 at 10 35 52 AM" src="https://user-images.githubusercontent.com/3698659/105888829-563c0400-5fc2-11eb-8159-bcc8dac99ec7.png">

**Comment by Askhento** [comment]
oh no it's my fault)))
Hah I used it for different SDF, will close the issue.
sorry
