### ISSUE TITLE
Array uniforms

### ISSUE THREAD

**Issue by Askhento** [aferriss/sparksl-shader-examples#4]
Is there any way to use vec4[] as uniform?

**Comment by aferriss** [comment]
I believe it's not currently supported by p5. You could send a bunch of different vec4s though. 

If you want the feature, I'd suggest opening an issue on the p5 repo to see if there is interest, and then making a pull request if you've got it implemented yourself.

Here's the relevant line: https://github.com/processing/p5.js/blob/810ba0850111016b9bfb8b9683617ed4079abe87/src/webgl/p5.Shader.js#L362

**Comment by Askhento** [comment]
But this is not p5

**Comment by aferriss** [comment]
Oh, actually, I think I'm wrong and it is implemented here. I haven't tried it though!
https://github.com/processing/p5.js/blob/810ba0850111016b9bfb8b9683617ed4079abe87/src/webgl/p5.Shader.js#L432

You can try `shader.setUniform("myUniform", [[0, 1, 0, 1], [1,0,01]]);`

And then in your shader:
`uniform vec4[2] myUniform;`

**Comment by aferriss** [comment]
OH! Haha, woops. No in SparkSL, uniform arrays are not currently supported.

**Comment by Askhento** [comment]
At least I know that p5js is capable!
