### ISSUE TITLE
TextureEnv  LOD?

### ISSUE THREAD

**Issue by Askhento** [aferriss/sparksl-shader-examples#7]
I was able to make a little hack with TextureEnv

```glsl
  std::TextureEnv envTexture = std::TextureEnv(
    [](vec3 dir) { 
        return vec4(1.0);
    }, 
    [](vec3 dir, float f) {
        return vec4(1.0);
    }
  );
```

Which is a dummy constructor and it works. There are two lambda functions, one of them require a float parameter, which seems like a LOD level to me. But if you try something like:

```glsl
    vec4 col = envTexture.sampleLod(vec3(1.0), 1.0);
```

You get an error that no such key in the struct.

**Comment by aferriss** [comment]
Hi @Askhento 

I'm not sure I'm following here. Are you saying that 
envTexture.sample(vec3(1)); works but .sampleLod(vec3(1), 1); does not?

In my testing, .sample(vec3(1)) did compile but wasn't producing any output except white.

**Comment by Askhento** [comment]
Yes, I am saying that there are should be some function with two parameters like this
```glsl
vec4 col = envTexture.someNameOfFunciton(vec3(1.0), 1.0);
```
But I get compile error because I don't know the name of it.

**Comment by aferriss** [comment]
Hi @Askhento sorry to say that the function in question doesn't exist (to my knowledge). I'm going to close this issue but feel free to reopen if you have more questions.
